<div>
    <h2><?php echo 'SOHAN you did it' ?></h2>
</div>
<?php $posts = $this->getNews(); ?>
<?php foreach ($posts as $post): ?>
    <h3><?php echo $post->getTitle(); ?></h3>
<?php endforeach; ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>