<div>
    <h2><?php echo 'SOHAN you did it' ?></h2>
</div>
<?php $posts = $this->getNews(); ?>
<?php foreach ($posts as $post): ?>
    <h2>
        <a href="/news/post/view/id/<?php echo $post->getNewsId(); ?>">
            <?php echo $post->getTitle(); ?>
        </a>
    </h2>
<?php endforeach; ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>