<?php $posts = $this->getNews(); ?>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="/news/post/view/id/<?php echo $post->getNewsId(); ?>"><?php echo $post->getTitle(); ?></a></h2>
            <h3><?php echo $post->getDate(); ?></h3>
        </div>
        <div class="postContent"><?php echo $post->getAnnounce(); ?></div>
    </div>
<?php endforeach; ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>