<?php $post = $this->getPost(); ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo Mage::getUrl('news/post/view', array('id' => $post->getNewsId())); ?>"><?php echo $post->getTitle(); ?></a></h2>
            <h3><?php echo $post->getDate(); ?></h3>
        </div>
        <div class="postContent"><?php echo $post->getContent(); ?></div>
    </div>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>