<?php if ($posts = $this->getLast()): ?>
    <div class="widget-latest">
        <h2><?php echo Mage::helper('news')->__('Latest News'); ?></h2>
        <ul>
            <?php foreach ($posts as $post): ?>
                <li><a href="/news/post/view/id/<?php echo $post->getNewsId(); ?>" ><?php echo $post->getTitle(); ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>